/**
 * zone: 0 схватка, 7 точки, 5 мокрые войны — real; остальные — virtual
 * mode: real | virtual (см. isVirtualZone)
 * playUrl: только если на сайте есть «Вход в игру»
 */
window.GAMES = [
  {
    id: 81885,
    num: 422,
    title: "ГРОЗДИ-2 первая игра сезона [Made EN Russia]",
    zone: 0,
    typeName: "Схватка",
    mode: "real",
    status: "live",
    start: "16.05.2026 10:00",
    fee: "1 500 ₽",
    authors: "SPORTWRX, Realist",
    poster: "https://d1.endata.cx/data/games/81885/анонс.jpg",
    url: "/GameDetails.aspx?gid=81885",
    playUrl: "/gameengines/encounter/play/81885",
  },
  {
    id: 77734,
    num: 256,
    title: "ИГРА ДЛЯ НОВИЧКОВ - обучение, знакомство с движком",
    zone: 0,
    typeName: "Схватка",
    mode: "real",
    status: "live",
    start: "сейчас",
    fee: "бесплатно",
    authors: "—",
    poster: null,
    url: "/GameDetails.aspx?gid=77734",
    playUrl: "/gameengines/encounter/play/77734",
  },
  {
    id: 82000,
    num: 429,
    title: "Доминанта big img XXL [свалка, до 4 игроков]",
    zone: 1,
    typeName: "Мозговой штурм",
    mode: "virtual",
    status: "live",
    start: "сейчас",
    fee: "бесплатно",
    authors: "nickoff",
    poster: null,
    url: "/GameDetails.aspx?gid=82000",
    playUrl: "/gameengines/encounter/play/82000",
  },
  {
    id: 82105,
    num: 431,
    title: "Словорезки из-под ножа /гибкий старт/",
    zone: 1,
    typeName: "Мозговой штурм",
    mode: "virtual",
    status: "live",
    start: "сейчас",
    fee: "500 ₽",
    authors: "Джэм",
    poster: null,
    url: "/GameDetails.aspx?gid=82105",
    playUrl: "/gameengines/encounter/play/82105",
  },
  {
    id: 81369,
    num: 406,
    title: "Игра 2 [Made EN Russia] Пятница 13-е",
    zone: 0,
    typeName: "Схватка",
    mode: "real",
    status: "upcoming",
    start: "30.05.2026 21:13",
    fee: "бесплатно",
    authors: "Roscha, General-Jungler",
    poster: null,
    url: "/GameDetails.aspx?gid=81369",
    playUrl: null,
  },
  {
    id: 79677,
    num: 356,
    title: "Игра 3 [Made EN Russia] Дезориентация",
    zone: 0,
    typeName: "Схватка",
    mode: "real",
    status: "upcoming",
    start: "27.06.2026 09:00",
    fee: "2 500 ₽",
    authors: "SENATORR",
    poster: null,
    url: "/GameDetails.aspx?gid=79677",
    playUrl: null,
  },
  {
    id: 79838,
    num: 362,
    title: "Олимпийский Енот (гибкий старт)",
    zone: 1,
    typeName: "Мозговой штурм",
    mode: "virtual",
    status: "upcoming",
    start: "14.04.2027 13:00",
    fee: "2 en usd",
    authors: "Джэм",
    poster: null,
    url: "/GameDetails.aspx?gid=79838",
    playUrl: null,
  },
  {
    id: 81000,
    num: 300,
    title: "Ковровская викторина (тест)",
    zone: 9,
    typeName: "Викторина",
    mode: "virtual",
    status: "upcoming",
    start: "01.08.2026 18:00",
    fee: "бесплатно",
    authors: "Оргштаб",
    poster: null,
    url: "/GameDetails.aspx?gid=81000",
    playUrl: null,
  },
];

window.TYPE_ICON = (zone) =>
  `https://cdn.endata.cx/images/icons/forum/type.${zone}.gif?v1`;

/** Реальные: zone 0, 7, 5. Остальные — виртуальные */
window.isVirtualZone = (zone) => zone !== 0 && zone !== 7 && zone !== 5;
